### ISSUE TITLE
V úpravě úkolů se kalendář otevírá se špatným datumem

### ISSUE THREAD

**Issue by rblaha15** [jaro-jaro/gymceska-mobile#11]
Pokud je u daného úkolu aktuálně nastaveno 0. 0., nebo cokoliv, co není datum, otevře se to na dnešku, pokud ale je to reálné datum, otevře se to v ten den tohoto ŠKOLNÍHO ROKU (jak už sis mohl všimnout v řazení, změnu šk. roku máme 30.6./1.7.):

| Akt. měs. | Vybraný měs. | Rok |
|--------|--------|--------|
| ≥ 7 | ≥ 7 | Tento rok |
| ≥ 7 | < 7 | Příští rok |
| < 7 | ≥ 7 | Minulý rok |
| < 7 | < 7 | Tento rok |

**Comment by rblaha15** [comment]
@0ndra0

**Comment by rblaha15** [comment]
Hint: `LicalDate.of()`

**Comment by 0ndra0** [comment]
to mi došlo a chtěl jsem vyzkoušet, co by se stalo kdybych dal 32. ledna, ale nic jsem nezkusil
